config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :lists do
    resources :bookmarks, only: [:new, :create, :destroy]
  end

  root to: "lists#index"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, presence: true
  validates :list, presence: true
  validates :comment, length: { minimum: 6 }

  validates :movie_id, uniqueness: {
    scope: :list_id
  }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.new(set_params)
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def set_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def edit
  end

  def update
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  def update
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
 <%= f.input :comment %>
 <%= f.association :movie%>
 <%= f.submit %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/69af44d716.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <div class="main-container">
    <div class="header">
      <div class="onglets">
        <p><%= link_to "Dashboard", lists_path, class:"dashboard" %></p>
        <p>Movies</p>
        <p>Series</p>
        <p>Kids</p>
      </div>
      <div class="avatar">
        <img src="" alt="">
        <div class="search-container">
          <i class="fa-brands fa-searchengin search-icon"></i>
          <input type="text" class="search-bar" placeholder="Search a movie">
        </div>
      </div>
    </div>
    <body>
    <%= yield %>
    </body>
  </div>


</html>

app/views/lists/index.html.erb
<div class="title-container">
  <h1>Create your movies list</h1>
  <button class= "btn-primary">
    <%= link_to "Add a movie list", new_list_path, class: "text-btn" %>
  </button>
</div>

<ul>
  <% @lists.each do |list| %>
   <li><%= list.name %></li>
   <span><%= link_to "See details", list_path(list) %></span>
  <% end %>
</ul>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
 <%= f.input :name %>
 <%= f.submit %>
<%end%>

<button>
  <%= link_to "Go back", lists_path %>
</button>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<% @list.bookmarks.each do |bookmark| %>
  <li><%= bookmark.comment %></li>
  <img src="<%= bookmark.movie.poster_url%>", class="img" >
  <span><%= bookmark.movie.title %><span>
  <button><%= link_to "Delete bookmark", list_bookmark_path(@list, bookmark),
          data: { turbo_method: :delete,  turbo_confirm: "Are you sure?" }%></button>
<% end %>

<div>
  <button>
    <%= link_to "Delete",  list_path(@list),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </button>

  <button>
    <%=link_to "Add bookmark", new_list_bookmark_path(@list) %>
  </button>
</div>